### PR TITLE
Allow User-added-CAs in Android 7.

### PR DESCRIPTION
**Pull request by maikbrueggemann**
See:
	- https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html
	- https://developer.android.com/training/articles/security-config.html

### CODE REVIEW

**Comment by maikbrueggemann** [comment]
Maybe related to #333

**Comment by JulienVdG** [comment]
I can confirm this works. I've been waiting to get my new computer before trying to fix this. But this pull request fix exactly my issue.
Thanks Nils for maintaining this tt-rss client, and thanks maikbrueggemann for beating me at fixing this issue that prevented me to read my feeds on my phone for too long now.
Back to reading 200 unread posts :)

**Comment by nning** [comment]
I can also confirm this works for me.

**Comment by micha137** [comment]
+1

**Pull request merged**
